In [1]:
#THIS SCRIPT IS ALL ABOUT TRYING OUT MY SMC FOR THEOREM 1 AND SEEING WHAT HAPPENS!

print("THIS SCRIPT USES *WINDOWS* FILEPATHS. CHANGE FOR LINUX!! (inc the additional 'proj_code' at start for some reason)")

####################################################################################
print("Imports...")
import random

import numpy as np
import torch
from torch import optim
from tqdm import tqdm

import gymnasium as gym

from stable_baselines3 import A2C,PPO


from stable_baselines3.common.logger import configure


import fabian.envs.khazad_dum_gymn 

import matplotlib.pyplot as plt


####################################################################################
print("Setting up...")
model_save_path = "C:\\Users\\fabia\\Documents\\GitHub\\MetaStableBaselines3\\proj_code\\saved_models\\19May_TestingMAML_A2C" #simulatenously testing my new maml syntax out and doing PPO (if somethings up, then try A2C with my new maml syntax to see if its my PPO that is wrong or the MAML syntax (too?))

device='cpu'
adapt_lr =  7e-4
adapt_timesteps = 32*4 #for this enviornment, each episode is exactly 32 timesteps, so multiple of 32 means full number of eps experienced for each task
eval_timesteps = 100
M=1

env = gym.make("KhazadDum-v1") # can access wrapped env with "env.unwrapped" (e.g. to reset task)
env.unwrapped.exp_bonus = 1; env.unwrapped.bridge_bonus_factor = 2 #this should incentivise getting to the target asap, and incentivise going onto the bridge


meta_agent = A2C("MlpPolicy", env, verbose=0, learning_rate=adapt_lr, device=device,
                 meta_learning=True, M=M, adapt_timesteps=adapt_timesteps, eval_timesteps=eval_timesteps)
meta_agent.policy.load_state_dict(torch.load(f"{model_save_path}\\final", weights_only=True))

####################################################################################



THIS SCRIPT USES *WINDOWS* FILEPATHS. CHANGE FOR LINUX!! (inc the additional 'proj_code' at start for some reason)
Imports...


C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:649: SyntaxWarning: invalid escape sequence '\e'
  Find risk bound \epsilon and performance guarantee \\tilde{J} s.t. {policy} is certifiably robust with {confidence_level}.
C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:672: SyntaxWarning: invalid escape sequence '\e'
  Find risk bound \epsilon and performance guarantee \\tilde{J} s.t. {policy} is certifiably robust with {confidence_level}.
C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:712: SyntaxWarning: invalid escape sequence '\e'
  Find risk bound \epsilon and performance guarantee \\tilde{J} s.t. {policy} is certifiably robust with {confidence_lev

Setting up...


c:\Users\fabia\anaconda3\envs\projdist\Lib\site-packages\gymnasium\envs\registration.py:487: UserWarning: WARN: The environment creator metadata doesn't include `render_modes`, contains: ['render.modes']
  logger.warn(


<All keys matched successfully>

In [22]:

eta = 0.1
gamma = 0.01 #small to be pretty confient in our bounds (therefore they will be pretty poor guarantees i suppose? hopefully that is what should happen -big t!)
tasks = 120
k=0

In [23]:
returns = meta_agent.sample_returns(tasks=tasks, repeats_per_task=30)
print(returns)

100%|██████████| 120/120 [4:10:06<00:00, 125.05s/it] 


{0: [tensor(-0.3141), tensor(-0.5577), tensor(-0.2135), tensor(-0.3919), tensor(-0.5172), tensor(-0.3621), tensor(-0.1571), tensor(-0.3230), tensor(-0.2274), tensor(-0.1900), tensor(-0.2169), tensor(-0.5554), tensor(-0.6933), tensor(-0.2097), tensor(-0.1958), tensor(0.0462), tensor(-0.0262), tensor(-0.2409), tensor(-0.2495), tensor(-0.6754), tensor(-0.9721), tensor(-0.3820), tensor(-0.4854), tensor(-0.2329), tensor(-1.1191), tensor(-0.3772), tensor(-0.8377), tensor(0.0399), tensor(-0.6654), tensor(-0.2523)], 1: [tensor(-0.1778), tensor(0.0896), tensor(0.0017), tensor(0.0360), tensor(-0.2491), tensor(0.0012), tensor(0.0573), tensor(0.0388), tensor(0.0579), tensor(0.0247), tensor(0.0590), tensor(0.0332), tensor(-0.2069), tensor(0.0157), tensor(0.0598), tensor(-0.1045), tensor(0.0345), tensor(0.0709), tensor(-0.1333), tensor(-0.0299), tensor(-0.2141), tensor(0.0609), tensor(0.0623), tensor(0.0498), tensor(0.0666), tensor(-0.1485), tensor(0.0562), tensor(0.0399), tensor(0.0742), tensor(0.0

In [ ]:
min(returns.values())

0

In [ ]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c2(gamma, eta, 0, returns, (-0.6,0.6))#(a,b)) #TODO: intereswtingly too conservative bounds here may make c3 better!
print((epsilon, guarantee))

  0%|          | 0/121 [00:00<?, ?it/s]

C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:552: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  epsilon = fsolve(self._theorem2_epsiloneq, starting_point, args=(k,K,n,gamma,eta))
 98%|█████████▊| 118/121 [02:08<00:03,  1.09s/it]

(array([0.05982162]), np.float64(-1.0329530692093885))


In [32]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c2(gamma, eta, 0, returns, (-0.8,0.1))#(a,b)) #TODO: intereswtingly too conservative bounds here may make c3 better!
print((epsilon, guarantee))

  0%|          | 0/121 [00:00<?, ?it/s]C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:552: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  epsilon = fsolve(self._theorem2_epsiloneq, starting_point, args=(k,K,n,gamma,eta))
 98%|█████████▊| 118/121 [01:07<00:01,  1.74it/s]

(array([0.05982162]), np.float64(-0.9498401623959329))


In [28]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c2(gamma, eta, 10, returns, (-0.6,0.6))#(a,b)) #TODO: intereswtingly too conservative bounds here may make c3 better!
print((epsilon, guarantee))

 98%|█████████▊| 109/111 [00:51<00:00,  2.13it/s]

(array([0.15948922]), np.float64(-0.6057993626587902))


In [33]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c2(gamma, eta, 5, returns, (-0.8,0.1))#(a,b)) #TODO: intereswtingly too conservative bounds here may make c3 better!
print((epsilon, guarantee))

 97%|█████████▋| 113/116 [01:07<00:01,  1.68it/s]

(array([0.11160045]), np.float64(-0.6065565687413004))


In [34]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c2(gamma, eta, 10, returns, (-0.8,0.1))#(a,b)) #TODO: intereswtingly too conservative bounds here may make c3 better!
print((epsilon, guarantee))

 98%|█████████▊| 109/111 [00:59<00:01,  1.84it/s]

(array([0.15948922]), np.float64(-0.5226864558453348))


In [6]:
bounding_returns = meta_agent.sample_returns(tasks=40, repeats_per_task=1)
bounding_returns = [i[0] for i in bounding_returns.values()]

100%|██████████| 40/40 [03:22<00:00,  5.06s/it]


In [40]:
more_bounding_returns = meta_agent.sample_returns(tasks=120, repeats_per_task=1)
bounding_returns = bounding_returns+ [i[0] for i in more_bounding_returns.values()]

100%|██████████| 120/120 [13:37<00:00,  6.81s/it]


In [52]:
a = min(bounding_returns)
b = max(bounding_returns)
n_br = 100_000#len(bounding_returns)
print((a,b))
print(n_br)
x = np.power(1/n_br, n_br/(n_br-1))
gamma_hat = 2*(1+x-np.power(x,1/n_br))
gamma_hat*50

(tensor(-0.9683), tensor(0.0986))
100000


np.float64(0.012512262746522396)

In [46]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c3(gamma, 0.7, k, bounding_returns, returns) #small max ks just to cehck what gamma_2 ends up as
print((epsilon, guarantee))

gamma_2=0.7913130471912166


 23%|██▎       | 28/121 [00:04<00:14,  6.35it/s]

((24, array([0.8190917])), tensor(-0.9961))


In [47]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c3(gamma, 0.07, k, bounding_returns, returns) #small max ks just to cehck what gamma_2 ends up as
print((epsilon, guarantee))

gamma_2=0.7913130471912166


  0%|          | 0/121 [00:00<?, ?it/s]C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:552: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  epsilon = fsolve(self._theorem2_epsiloneq, starting_point, args=(k,K,n,gamma,eta))
 17%|█▋        | 20/121 [00:02<00:14,  6.92it/s]

((18, array([0.90689483])), tensor(-0.9961))


In [39]:
epsilon, guarantee =  meta_agent.task_risk_SMC_c3(gamma, eta, k, bounding_returns, returns, max_Ks=2)
print((epsilon, guarantee))

gamma_2=0.9706507589896629


  0%|          | 0/3 [00:00<?, ?it/s]C:\Users\fabia\Documents\GitHub\MetaStableBaselines3\proj_code\stable-baselines3-master\stable-baselines3-master\stable_baselines3\common\on_policy_algorithm.py:552: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  epsilon = fsolve(self._theorem2_epsiloneq, starting_point, args=(k,K,n,gamma,eta))
100%|██████████| 3/3 [00:04<00:00,  1.49s/it]

(-1, tensor(-0.9730))
